export const teaching_data = {
    'es' : [
            {
                    'name'          : 'Entornos de enseñanza y aprendizaje mediados por tecnologías',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Curso Documento',
                    'year'          : '2021',
                    'description'   : 'Falta',
                    'participants'  : '126',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+EMT+2021_2+type@asset+block@about_orientaciones.jpg',
            },
            {
                    'name'          : 'Enseñanza Mediada por Tecnologías con Perspectiva de Género',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Micro Curso',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '37',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C9+2022_2+type@asset+block@portada_2022_09.jpg',
            },
            {
                    'name'          : 'Entornos de Enseñanza y Aprendizaje Mediados por Tecnologías',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Micro Curso',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '41',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C2+2022_2+type@asset+block@portada_2022_02.jpg',
            },
            {
                    'name'          : 'Certificación del Programa de Formación para Docentes',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '28',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+CF+2023_1+type@asset+block@portada_2022_10__2_.jpg',
            },
            {
                    'name'          : 'Conociendo EOL',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '109',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+C1+2022_1+type@asset+block@portada_2022_01.jpg',
            },
            {
                    'name'          : 'Entornos de Enseñanza y Aprendizaje Mediados por Tecnologías',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '104',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C2+2022_2+type@asset+block@portada_2022_02.jpg',
            },
            {
                    'name'          : 'Enseñanza Mediada por Tecnologías con Perspectiva de Género',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '81',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C9+2022_2+type@asset+block@portada_2022_09.jpg',
            },
            {
                    'name'          : 'Herramientas tecnológicas para la evaluación',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '74',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C6+2022_2+type@asset+block@portada_2022_06.jpg',
            },
            {
                    'name'          : 'Metodologías Activas de Enseñanzas',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '68',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C3+2022_2+type@asset+block@portada_2022_03.jpg',
            },
            {
                    'name'          : 'Planificación y cubicación de un curso',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2022',
                    'description'   : 'Falta',
                    'participants'  : '64',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C4+2022_2+type@asset+block@portada_2022_04.jpg',
            },
            {
                    'name'          : 'La Producción de material didáctico para entornos virtuales de aprendizaje',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '57',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C5+2022_2+type@asset+block@portada_2022_05.jpg',
            },
            {
                    'name'          : 'Movilidad virtual/hyflex',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '55',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C10+2022_2+type@asset+block@Hyflex.jpg',
            },
            {
                    'name'          : 'Analítica y evaluación de la implementación de un curso mediado por tecnología',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Malla EOL',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '53',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:vlabx+C7+2022_2+type@asset+block@portada_2022_07.jpg',
            },
            {
                    'name'          : 'Curso de demostración EOL',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : 'Curso Demo',
                    'year'          : '2021',
                    'description'   : 'Falta',
                    'participants'  : '58',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+eol-demo+2020_1+type@asset+block@logo_v_EOL_normal2.png',
            },
            {
                    'name'          : 'Docencia Mediada por Tecnologías: el siguiente desafío',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '33',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+C12+2023_2+type@asset+block@about_Docencia.jpg',
            },
            {
                    'name'          : 'Herramientas de comunicación e interacción con el estudiante online',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2020',
                    'description'   : 'Falta',
                    'participants'  : '225',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+EOL-100+2020_1+type@asset+block@curso1_2.jpg',
            },
            {
                    'name'          : 'Herramientas para la evaluación en entornos virtuales de aprendizaje',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2020',
                    'description'   : 'Falta',
                    'participants'  : '206',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+EOL-200+2020_2+type@asset+block@curso2.jpg',
            },
            {
                    'name'          : 'IA en Educación Superior: Desafíos y Transformaciones',
                    'org'           : 'Oficina de Educación Online - Vicerrectoría de Tecnologías de la Información',
                    'tier'          : '',
                    'year'          : '2023',
                    'description'   : 'Falta',
                    'participants'  : '102',
                    'course_id'     : '',
                    'image'         : 'https://eol.uchile.cl/asset-v1:eol+C11+2023_1+type@asset+block@EOL_cursoAI_01.jpg',
            }
    ]
}
