name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-front-eol:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build the Docker image
      run: docker build . --tag ghcr.io/eol-uchile/portal-eol:${GITHUB_SHA}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: eolito
        password: ${{ secrets.CR_PAT }}

    - name: Push to Github Container Registry
      run: |
        docker push ghcr.io/eol-uchile/portal-eol:${GITHUB_SHA}

